export const apiConnectionMap = [
  {
    endpoint: "/api/auth/register",
    method: "POST",
    pages: ["/signup"],
    components: ["SignupPage"],
    hook: "useRegister",
    service: "authService.register",
    zustand: "auth-store.setSession",
    navigation: "/signup -> /dashboard",
    auth: "public",
    loading: "register.isPending",
    error: "register.error",
    optimistic: "no",
    invalidates: ["auth"]
  },
  {
    endpoint: "/api/auth/login",
    method: "POST",
    pages: ["/login"],
    components: ["LoginForm"],
    hook: "useLogin",
    service: "authService.login",
    zustand: "auth-store.setSession",
    navigation: "/login -> redirect param or /dashboard",
    auth: "public",
    loading: "login.isPending",
    error: "login.error",
    optimistic: "no",
    invalidates: ["auth"]
  },
  {
    endpoint: "/api/auth/logout",
    method: "POST",
    pages: ["TopNav"],
    components: ["TopNav"],
    hook: "useLogout",
    service: "authService.logout",
    zustand: "auth-store.clearSession",
    navigation: "any protected page -> /",
    auth: "authenticated",
    loading: "button action",
    error: "local cleanup still runs",
    optimistic: "yes, clears local session immediately after request attempt",
    invalidates: ["queryClient.clear"]
  },
  {
    endpoint: "/api/auth/refresh-token",
    method: "POST",
    pages: ["all API pages"],
    components: ["apiClient response interceptor"],
    hook: "implicit",
    service: "authService.refreshToken",
    zustand: "localStorage token keys",
    navigation: "stays on current page or redirects to /login",
    auth: "refresh token",
    loading: "transparent retry",
    error: "redirect on failed refresh",
    optimistic: "no",
    invalidates: ["original request retry"]
  },
  {
    endpoint: "/api/auth/me",
    method: "GET",
    pages: ["all pages through AppProviders"],
    components: ["SessionBootstrap"],
    hook: "useMe",
    service: "authService.me",
    zustand: "auth-store.user/profile",
    navigation: "session persistence",
    auth: "authenticated",
    loading: "background bootstrap",
    error: "interceptor handles 401",
    optimistic: "no",
    invalidates: ["auth"]
  },
  {
    endpoint: "/api/profiles/:username",
    method: "GET",
    pages: ["/profile/[username]"],
    components: ["ProfilePage", "ProfileHeader", "SkillSection", "BadgeDisplay"],
    hook: "useProfile",
    service: "profileService.get",
    zustand: "none",
    navigation: "Profile links -> /profile/[username]",
    auth: "public",
    loading: "profile.isLoading eligible",
    error: "not-found fallback eligible",
    optimistic: "no",
    invalidates: ["profile username"]
  },
  {
    endpoint: "/api/profiles/me/update",
    method: "PATCH",
    pages: ["/settings/profile"],
    components: ["ProfileSettingsPage"],
    hook: "useUpdateProfileMutation",
    service: "profileService.updateMe/profileApi.update",
    zustand: "auth-store.profile refresh through /auth/me",
    navigation: "/settings/profile -> /profile/[username]",
    auth: "authenticated",
    loading: "updateProfile.isPending",
    error: "updateProfile.error",
    optimistic: "no",
    invalidates: ["auth.me", "profiles"]
  },
  {
    endpoint: "/api/uploads/asset",
    method: "POST",
    pages: ["/settings/profile"],
    components: ["ProfileSettingsPage", "ResumeUploader"],
    hook: "useUploadProfileAssetMutation",
    service: "uploadsService.uploadAvatar/uploadCover",
    zustand: "auth-store.profile after refresh",
    navigation: "settings upload -> profile display",
    auth: "authenticated",
    loading: "upload mutation isPending eligible",
    error: "upload mutation error eligible",
    optimistic: "no",
    invalidates: ["auth.me", "profiles"]
  },
  {
    endpoint: "/api/uploads/resume",
    method: "POST",
    pages: ["/settings/profile"],
    components: ["ProfileSettingsPage", "ResumeUploader"],
    hook: "useUploadResumeMutation",
    service: "uploadsService.uploadResume",
    zustand: "auth-store.profile after refresh",
    navigation: "settings upload -> profile resume",
    auth: "authenticated",
    loading: "uploadResume.isPending eligible",
    error: "uploadResume.error eligible",
    optimistic: "no",
    invalidates: ["auth.me", "profiles"]
  },
  {
    endpoint: "/api/ideas",
    method: "GET",
    pages: ["/ideas", "/dashboard"],
    components: ["IdeaCard", "DashboardPage"],
    hook: "useIdeas",
    service: "ideasService.list",
    zustand: "none",
    navigation: "Landing -> Explore Ideas",
    auth: "public",
    loading: "Skeleton cards",
    error: "React Query error state eligible",
    optimistic: "no",
    invalidates: ["ideas"]
  },
  {
    endpoint: "/api/ideas/trending",
    method: "GET",
    pages: ["/ideas"],
    components: ["TrendingIdeas"],
    hook: "useTrendingIdeas",
    service: "ideasService.trending",
    zustand: "none",
    navigation: "/ideas trending chips -> /ideas/[id]",
    auth: "public",
    loading: "background section",
    error: "empty chips fallback",
    optimistic: "no",
    invalidates: ["ideas", "trending"]
  },
  {
    endpoint: "/api/ideas",
    method: "POST",
    pages: ["/ideas/create"],
    components: ["IdeaEditor"],
    hook: "useCreateIdea",
    service: "ideasService.create",
    zustand: "none",
    navigation: "/ideas/create -> /ideas/[slug]",
    auth: "authenticated",
    loading: "createIdea.isPending",
    error: "createIdea.error",
    optimistic: "no",
    invalidates: ["ideas"]
  },
  {
    endpoint: "/api/ideas/:slug",
    method: "GET/PATCH/DELETE",
    pages: ["/ideas/[id]"],
    components: ["IdeaDetailPage", "RelatedIdeas"],
    hook: "useIdea",
    service: "ideasService.get/update/delete",
    zustand: "none",
    navigation: "/ideas -> /ideas/[id] -> /teams",
    auth: "GET public, mutations authenticated owner",
    loading: "Loader",
    error: "Idea not found fallback",
    optimistic: "delete/update can invalidate",
    invalidates: ["ideas", "ideas slug"]
  },
  {
    endpoint: "/api/ideas/:slug/upvote",
    method: "POST",
    pages: ["/ideas/[id]", "/ideas"],
    components: ["UpvoteButton", "IdeaCard"],
    hook: "useIdeaAction",
    service: "ideasService.upvote",
    zustand: "none",
    navigation: "stays on idea/card",
    auth: "authenticated",
    loading: "mutation pending eligible",
    error: "mutation error eligible",
    optimistic: "required for card/detail count",
    invalidates: ["ideas"]
  },
  {
    endpoint: "/api/ideas/:slug/bookmark",
    method: "POST",
    pages: ["/ideas/[id]", "/ideas"],
    components: ["BookmarkButton", "IdeaCard"],
    hook: "useIdeaAction",
    service: "ideasService.bookmark",
    zustand: "none",
    navigation: "stays on idea/card",
    auth: "authenticated",
    loading: "mutation pending eligible",
    error: "mutation error eligible",
    optimistic: "required for saved state",
    invalidates: ["ideas"]
  },
  {
    endpoint: "/api/ideas/:slug/comments",
    method: "GET/POST",
    pages: ["/ideas/[id]"],
    components: ["CommentThread", "CommentInput"],
    hook: "useIdeaComments/useCreateIdeaComment",
    service: "commentsService.comments/comment",
    zustand: "none",
    navigation: "Idea Details comments",
    auth: "GET public, POST authenticated",
    loading: "comments section eligible",
    error: "mutation/query error eligible",
    optimistic: "yes, optimistic comment row",
    invalidates: ["ideas slug comments"]
  },
  {
    endpoint: "/api/ideas/:slug/comments/:commentId",
    method: "PATCH/DELETE",
    pages: ["/ideas/[id]"],
    components: ["CommentThread"],
    hook: "useIdeaCommentAction",
    service: "commentsService.updateComment/deleteComment",
    zustand: "none",
    navigation: "Idea Details comments",
    auth: "authenticated comment owner",
    loading: "action pending eligible",
    error: "action error eligible",
    optimistic: "yes for edit/delete",
    invalidates: ["ideas slug comments"]
  },
  {
    endpoint: "/api/teams",
    method: "GET/POST",
    pages: ["/teams", "/projects", "/dashboard"],
    components: ["TeamBoard", "RoleCard"],
    hook: "useTeams/useCreateTeam",
    service: "projectsService.list/create",
    zustand: "none",
    navigation: "Build With Me -> Teams -> Workspace",
    auth: "GET public, POST authenticated",
    loading: "createTeam.isPending, list skeleton eligible",
    error: "createTeam.error",
    optimistic: "no",
    invalidates: ["teams"]
  },
  {
    endpoint: "/api/teams/:slug",
    method: "GET",
    pages: ["/workspace/[projectId]"],
    components: ["KanbanBoard", "MilestoneTracker", "RoleCard"],
    hook: "useTeam",
    service: "projectsService.get",
    zustand: "none",
    navigation: "/projects or /teams -> /workspace/[projectId]",
    auth: "public",
    loading: "workspace title fallback",
    error: "workspace fallback eligible",
    optimistic: "no",
    invalidates: ["teams slug"]
  },
  {
    endpoint: "/api/teams/:slug/roles",
    method: "POST",
    pages: ["/teams", "/workspace/[projectId]"],
    components: ["RoleCard", "ApplicantModal"],
    hook: "projectsService.addRole available",
    service: "projectsService.addRole",
    zustand: "none",
    navigation: "Team owner adds role",
    auth: "authenticated owner",
    loading: "mutation pending eligible",
    error: "mutation error eligible",
    optimistic: "no",
    invalidates: ["teams", "teams slug"]
  },
  {
    endpoint: "/api/teams/:slug/roles/:roleId/apply",
    method: "POST",
    pages: ["/teams"],
    components: ["ApplyButton", "RoleCard"],
    hook: "useApplyToTeamRole",
    service: "projectsService.apply",
    zustand: "none",
    navigation: "Teams -> application notification",
    auth: "authenticated",
    loading: "apply.isPending",
    error: "apply.error eligible",
    optimistic: "button shows Applied",
    invalidates: ["teams", "teams slug"]
  },
  {
    endpoint: "/api/teams/applications/:applicationId",
    method: "PATCH",
    pages: ["/workspace/[projectId]"],
    components: ["ApplicantModal"],
    hook: "useDecideTeamApplication",
    service: "projectsService.decideApplication",
    zustand: "none",
    navigation: "Owner workspace -> accept/reject",
    auth: "authenticated owner",
    loading: "mutation pending eligible",
    error: "mutation error eligible",
    optimistic: "optional",
    invalidates: ["teams"]
  },
  {
    endpoint: "/api/badges",
    method: "GET",
    pages: ["/achievements", "/profile/[username]"],
    components: ["BadgeCard", "BadgeDisplay"],
    hook: "useBadges",
    service: "leaderboardService.badges",
    zustand: "none",
    navigation: "Profile -> Achievements",
    auth: "public",
    loading: "badge grid eligible",
    error: "empty fallback eligible",
    optimistic: "no",
    invalidates: ["badges"]
  },
  {
    endpoint: "/api/badges/leaderboard",
    method: "GET",
    pages: ["/leaderboard", "/dashboard"],
    components: ["LeaderboardTable", "RankCard", "XPBar"],
    hook: "useLeaderboard",
    service: "leaderboardService.leaderboard",
    zustand: "none",
    navigation: "Navbar -> Leaderboard -> Profile",
    auth: "public",
    loading: "leaderboard list eligible",
    error: "empty fallback eligible",
    optimistic: "no",
    invalidates: ["leaderboard"]
  },
  {
    endpoint: "/api/notifications",
    method: "GET",
    pages: ["/notifications", "TopNav"],
    components: ["NotificationList", "NotificationDropdown", "NotificationBadge"],
    hook: "useNotifications",
    service: "notificationsService.list",
    zustand: "notification-store",
    navigation: "Dashboard <-> Notifications",
    auth: "authenticated",
    loading: "notifications query eligible",
    error: "query error eligible",
    optimistic: "no",
    invalidates: ["notifications"]
  },
  {
    endpoint: "/api/notifications/:id/read",
    method: "PATCH",
    pages: ["/notifications"],
    components: ["NotificationList"],
    hook: "useMarkNotificationRead",
    service: "notificationsService.markRead",
    zustand: "notification-store",
    navigation: "Notification -> linked page",
    auth: "authenticated",
    loading: "button pending eligible",
    error: "mutation error eligible",
    optimistic: "yes, marks read in cache immediately",
    invalidates: ["notifications"]
  },
  {
    endpoint: "/api/launches",
    method: "GET/POST",
    pages: ["/launches"],
    components: ["LaunchCard"],
    hook: "useLaunches",
    service: "launchesService.list/create",
    zustand: "none",
    navigation: "Workspace -> Product Launch",
    auth: "GET public, POST authenticated",
    loading: "launch grid eligible",
    error: "empty/error fallback eligible",
    optimistic: "no",
    invalidates: ["launches"]
  },
  {
    endpoint: "/api/launches/:slug",
    method: "GET/PATCH/DELETE",
    pages: ["/launches/[id]"],
    components: ["ProductGallery", "ReviewSection", "LaunchMetrics"],
    hook: "useLaunch",
    service: "launchesService.get/update/delete",
    zustand: "none",
    navigation: "/launches -> /launches/[id] -> /hiring",
    auth: "GET public, mutations authenticated owner",
    loading: "detail fallback eligible",
    error: "not-found fallback eligible",
    optimistic: "no",
    invalidates: ["launches", "launches slug"]
  },
  {
    endpoint: "/api/launches/:slug/upvote",
    method: "POST",
    pages: ["/launches/[id]"],
    components: ["LaunchMetrics"],
    hook: "launchesService.upvote available",
    service: "launchesService.upvote",
    zustand: "none",
    navigation: "stays on launch",
    auth: "authenticated",
    loading: "mutation pending eligible",
    error: "mutation error eligible",
    optimistic: "recommended",
    invalidates: ["launches"]
  },
  {
    endpoint: "/api/jobs",
    method: "GET/POST",
    pages: ["/hiring"],
    components: ["JobCard", "StartupHiringBoard"],
    hook: "useJobs",
    service: "jobsService.list/create",
    zustand: "none",
    navigation: "Launch -> Hiring",
    auth: "GET public, POST authenticated",
    loading: "job grid eligible",
    error: "empty/error fallback eligible",
    optimistic: "no",
    invalidates: ["jobs"]
  },
  {
    endpoint: "/api/jobs/:slug",
    method: "GET/PATCH/DELETE",
    pages: ["/jobs/[id]"],
    components: ["ApplicationModal"],
    hook: "useJob",
    service: "jobsService.get/update/delete",
    zustand: "none",
    navigation: "/hiring -> /jobs/[id]",
    auth: "GET public, mutations authenticated owner",
    loading: "detail fallback eligible",
    error: "not-found fallback eligible",
    optimistic: "no",
    invalidates: ["jobs", "jobs slug"]
  },
  {
    endpoint: "/api/jobs/:slug/apply",
    method: "POST",
    pages: ["/jobs/[id]"],
    components: ["ApplicationModal"],
    hook: "useApplyToJob",
    service: "jobsService.apply",
    zustand: "none",
    navigation: "Job detail -> application submitted",
    auth: "authenticated",
    loading: "apply.isPending",
    error: "apply.error",
    optimistic: "success message",
    invalidates: ["jobs slug"]
  },
  {
    endpoint: "/api/ai/tools/:tool/run",
    method: "POST",
    pages: ["/ai-tools"],
    components: ["AiToolsPage"],
    hook: "useAiTool",
    service: "aiApi.runTool",
    zustand: "none",
    navigation: "Navbar -> AI Tools",
    auth: "authenticated",
    loading: "ai.isPending",
    error: "ai.error eligible",
    optimistic: "no",
    invalidates: []
  }
];

export const apiConnectionMapByEndpoint = apiConnectionMap.reduce((acc, item) => {
  acc[`${item.method} ${item.endpoint}`] = item;
  return acc;
}, {});
